import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProviders from "@/redux/providers";
import Notif from "@/components/notif";
import Loading from "@/components/loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Level Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ReduxProviders>
          <Loading />
          <Notif />
          <div className="bg-white text-gray-600 dark:bg-gray-900 dark:text-gray-300">
            <hr className="dark:border-gray-800 border-gray-200" />
            {children}
          </div>
        </ReduxProviders>
      </body>
    </html>
  );
}
